### ISSUE TITLE
org-ql error when trying to use org-sidebar

### ISSUE THREAD

**Issue by frednord** [alphapapa/org-sidebar#46] opened 2021-02-20 14:50 UTC
I get this message when trying to use `M-x org-sidebar` or any other org-sidebar-related commands:

`org-ql--def-query-string-to-sexp-fn: Symbol’s function definition is void: -on`

I'm using org-sidebar version 20201114.507

**Comment by jaxspades** [comment] 2021-02-21 21:46
I am also experiencing this issue on the most recent version in MELPA, as I installed today on Emacs 27.1.

**Comment by alphapapa** [comment] 2021-02-23 01:04
Probably caused by a transition ongoing in the `dash` package with regard to `dash-functional `.

**Comment by jaxspades** [comment] 2021-02-23 02:22
> Probably caused by a transition ongoing in the `dash` package with regard to `dash-functional `.

Interesting, that would make sense, can we install a different version of dash to resolve this issue? If so, which version should I use?

Or should we use a different package all together?

**Comment by alphapapa** [comment] 2021-03-03 00:04
I can't look it up myself now, but please see Dash's tracker for the relevant issue.

**Comment by basil-conto** [comment] 2022-12-11 17:01
This was fixed in #45, right?

**Comment by alphapapa** [comment] 2024-01-01 23:33
Should have been, yes.  Thanks.

**Closed by alphapapa** 2024-01-01 23:33 UTC
